#!/bin/bash

# Function to display help
display_help() {
    echo "Usage: $0 <command> [options]"
    echo
    echo "Commands:"
    echo "  run_server [port]                  : Start PHP built-in server in the 'public' folder. If 'vendor' directory and 'composer.lock' file exist,"
    echo "                                       the script will run 'composer install' first. Default port is 5000 if not provided."
    echo "  migration_create <additional_text> : Create a migration file with a PHP extension, an incremental timestamp prefix,and additional text."
    echo "                                       The migration file is stored in the 'migrations' directory in the root folder."
    echo "  help                               : Display this help message."
}

# Function to run PHP built-in server
run_server() {
    local port=${1:-5000}  # Use the provided port or default to 5000

    # Navigate to the public folder
    cd "$(pwd)/public" || exit 1

    # Check if 'vendor' directory and 'composer.lock' file exist
    if [ ! -d "../vendor" ] || [ ! -f "../composer.lock" ]; then
        echo "'vendor' directory or 'composer.lock' file not found. Running 'composer install'..."
        # Run composer install
        composer install || { echo "Error running 'composer install'"; exit 1; }
    fi

    # Run PHP built-in server
    php -S localhost:"$port"
}

# Function to create migration file
migration_create() {
    local additional_text=$1
    local timestamp=$(date +"%Y%m%d%H%M%S")
    local migration_file="migrations/f${timestamp}_${additional_text}.php"
    
    echo "Creating migration file: $migration_file"
    
    # You can customize the migration content as needed
    echo "<?php
// Your migration content here
class f${timestamp}_${additional_text}
{
    public function up()
    {
        echo \"Applying migration\";
    }

    public function down()
    {
        echo \"Down migration\";
    }
}
    " > "$migration_file"
}

# Check if a valid command is provided
if [ $# -eq 0 ]; then
    echo "Error: Missing command."
    display_help
    exit 1
fi

# Process the command
case "$1" in
    run_server)
        run_server "${@:2}"
        ;;
    migration_create)
        migration_create "${@:2}"
        ;;
    help)
        display_help
        ;;
    *)
        echo "Invalid command: $1"
        display_help
        exit 1
        ;;
esac
